version: "3.3"
services:
  database:
    image: postgres
    volumes:
      - ./.dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "meowdb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "5432:5432"
